# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Git Tag
        run: |
          git describe --exact-match --abbrev=0 2>/dev/null || echo ""

      - name: Git branch
        run: |
          git rev-parse --abbrev-ref HEAD
