# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]
    tags:
      - "*.*"
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Git Tag
        run: |
          git describe --exact-match --abbrev=0 2>/dev/null || echo ""

      - name: Git branch
        run: |
          git rev-parse --abbrev-ref HEAD

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: env | sort

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

